import 'package:flutter/material.dart';
import 'package:nextdoorgym/utils/size.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  final Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  final Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [newTheme].
  void changeTheme(String newTheme) {
    _appTheme = newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generatorif (!_supportedCustomColor.containsKey(_appTheme)){  throw Exception(               "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");      } //return theme from map
    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator if (!_supportedColorScheme.containsKey(_appTheme)){   throw Exception(                "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");       }  //return theme from map
    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: colorScheme.errorContainer,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyMedium: TextStyle(
          color: Colors.white,
          fontSize: 13.fSize,
          fontFamily: 'Droid Sans',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: Colors.white,
          fontSize: 10.fSize,
          fontFamily: 'Droid Sans',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: Colors.white,
          fontSize: 43.fSize,
          fontFamily: 'Droid Sans',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: Colors.white,
          fontSize: 24.fSize,
          fontFamily: 'Droid Sans',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: Colors.white,
          fontSize: 20.fSize,
          fontFamily: 'Droid Sans',
          fontWeight: FontWeight.w400,
        ),
        titleMedium: TextStyle(
          color: Colors.white,
          fontSize: 18.fSize,
          fontFamily: 'Droid Sans',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static const primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFFC0B6FF),
    primaryContainer: Color(0XFF2E344A),
    secondaryContainer: Color(0XFFB4B4B4),

    // Error colors
    errorContainer: Color(0XFF2AD23A),
    onError: Color(0XFFEAEAEA),

    // On colors(text colors)
    onPrimary: Color(0XFF252727),
    onPrimaryContainer: Color(0XFF010101),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => const Color(0XFF000000);

  // Gray
  Color get gray800 => const Color(0XFF464646);
  Color get gray900 => const Color(0XFF1E1E1E);
  Color get gray90001 => const Color(0XFF252727);

  // Indigo
  Color get indigo150 => const Color.fromRGBO(192, 182, 255, 1);
  Color get indigo100 => const Color(0XFFC0B6FF);
  Color get indigo50 => const Color.fromARGB(255, 211, 205, 253);
  Color get indigo200 => const Color.fromARGB(255, 185, 174, 255);
  Color get indigo300 => const Color.fromARGB(255, 149, 134, 249);

  // White
  Color get whiteA700 => const Color(0XFFFFFFFF);
  Color get black9004c => const Color(0X4C000000);

  // BlueGray
  Color get blueGray600 => const Color(0XFF47548C);
  Color get blueGray900 => const Color(0XFF2E344A);

  // Gray
  Color get gray100 => const Color(0XFFF6F6F6);
  Color get gray600 => const Color(0XFF7B7B7B);
  Color get gray60001 => const Color(0XFF6E6E6E);

  // BlueGray
  Color get blueGray50 => const Color(0XFFF1F1F1);
  Color get blueGray90001 => const Color(0XFF2C2C2E);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
